version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viajaya-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: viajaya-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    ports:
      - "${PORT_DB}:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge