apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viajaya-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viajaya-db
  template:
    metadata:
      labels:
        app: viajaya-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - configMapRef:
                name: viajaya-db-config
            - secretRef:
                name: viajaya-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: viajaya-db
spec:
  type: ClusterIP
  selector:
    app: viajaya-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: viajaya-db-config
data:
  POSTGRES_DB: viajaya
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: viajaya-db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cm9vdA==